--------------------------------------------------------------------------------
select tab.owner,
       tab.table_name tabela,
       col.column_id,
       col.column_name coluna,
       col.data_type tipo,
       decode(col.data_precision, null, col.char_col_decl_length, col.data_precision) tamanho,
       col.nullable eh_nulo,
       comm.comments comentario
  from sys.all_tables       tab,
       sys.all_tab_columns  col,
       sys.all_col_comments comm
 where comm.column_name = col.column_name
   and comm.table_name  = col.table_name
   and tab.table_name   = col.table_name
   and tab.table_name   = 'COR_DOF'
   and tab.owner        = 'FISC33'
--------------------------------------------------------------------------------
select tab.owner,
       tab.table_name tabela,
       col.column_id,
       col.column_name coluna,
       col.data_type tipo,
       decode(col.data_precision, null, col.char_col_decl_length, col.data_precision) tamanho,
       col.nullable eh_nulo,
       comm.comments comentario
  from sys.all_tables       tab,
       sys.all_tab_cols     col,
       sys.all_col_comments comm
 where comm.column_name = col.column_name
   and comm.table_name  = col.table_name
   and tab.table_name   = col.table_name
   and tab.table_name   = 'COR_DOF'
   and tab.owner        = 'FISC33'
   and col.column_name in ('PRECO_TOTAL_M',
                           'PRECO_TOTAL_O',
                           'PRECO_TOTAL_P',
                           'PRECO_TOTAL_S',
                           'VL_ABAT_NT',
                           'VL_ADU',
                           'VL_ADU_ICMS',
                           'VL_AJUSTE_PRECO_TOTAL_M',
                           'VL_AJUSTE_PRECO_TOTAL_P',
                           'VL_AJUSTE_PRECO_TOTAL_S',
                           'VL_BASE_INSS_RET_PER',
                           'VL_COFINS_ST',
                           'VL_DESCONTO_NF',
                           'VL_DESPACHO',
                           'VL_DESP_CAR_DESC',
                           'VL_DESP_PORT',
                           'VL_FISCAL_M',
                           'VL_FISCAL_O',
                           'VL_FISCAL_P',
                           'VL_FISCAL_S',
                           'VL_FRETE',
                           'VL_FRETE_FERR_SUBSTITUIDA',
                           'VL_FRETE_LIQ',
                           'VL_FRETE_MM',
                           'VL_FRT_PV',
                           'VL_GRIS',
                           'VL_INSS',
                           'VL_OUTRAS_DESPESAS',
                           'VL_OUTROS_ABAT',
                           'VL_PEDAGIO',
                           'VL_PESO_TX',
                           'VL_PIS_ST',
                           'VL_SEC_CAT',
                           'VL_SEGURO',
                           'VL_SERV_NT',
                           'VL_TAXA_ADV',
                           'VL_TAXA_TERRESTRE',
                           'VL_TERC',
                           'VL_TFA',
                           'VL_TOTAL_BASE_COFINS',
                           'VL_TOTAL_BASE_COFINS_RET',
                           'VL_TOTAL_BASE_CSLL_RET',
                           'VL_TOTAL_BASE_ICMS',
                           'VL_TOTAL_BASE_ICMS_DIFA',
                           'VL_TOTAL_BASE_INSS',
                           'VL_TOTAL_BASE_INSS_RET',
                           'VL_TOTAL_BASE_IPI',
                           'VL_TOTAL_BASE_IRRF',
                           'VL_TOTAL_BASE_ISS',
                           'VL_TOTAL_BASE_PIS_PASEP',
                           'VL_TOTAL_BASE_PIS_RET',
                           'VL_TOTAL_BASE_SENAT',
                           'VL_TOTAL_BASE_SEST',
                           'VL_TOTAL_BASE_STF',
                           'VL_TOTAL_BASE_STF_FRONTEIRA',
                           'VL_TOTAL_BASE_STF_IDO',
                           'VL_TOTAL_BASE_STT',
                           'VL_TOTAL_COFINS',
                           'VL_TOTAL_COFINS_RET',
                           'VL_TOTAL_CONTABIL',
                           'VL_TOTAL_CSLL_RET',
                           'VL_TOTAL_FATURADO',
                           'VL_TOTAL_FCP',
                           'VL_TOTAL_ICMS',
                           'VL_TOTAL_ICMS_DIFA',
                           'VL_TOTAL_II',
                           'VL_TOTAL_INSS',
                           'VL_TOTAL_INSS_RET',
                           'VL_TOTAL_INSS_RET_PER',
                           'VL_TOTAL_IOF',
                           'VL_TOTAL_IPI',
                           'VL_TOTAL_IRRF',
                           'VL_TOTAL_ISENTO_ICMS',
                           'VL_TOTAL_ISS',
                           'VL_TOTAL_MAT_TERC',
                           'VL_TOTAL_OUTROS_ICMS',
                           'VL_TOTAL_PIS_PASEP',
                           'VL_TOTAL_PIS_RET',
                           'VL_TOTAL_SENAT',
                           'VL_TOTAL_SEST',
                           'VL_TOTAL_STF',
                           'VL_TOTAL_STF_FRONTEIRA',
                           'VL_TOTAL_STF_IDO',
                           'VL_TOTAL_STF_SUBSTITUIDO',
                           'VL_TOTAL_STT',
                           'VL_TRIBUTAVEL_DIFA',
                           'VL_TX_RED')
