STARTUP NOMOUNT
RESTORE CONTROLFILE FROM '[PATH]/[ARQUIVO BACKUP CONTROLFILE]';
SHUTDOWN ABORT
STARTUP MOUNT
RUN {
ALLOCATE CHANNEL CH01 TYPE DISK;
CATALOG START WITH '[PATH_ARQUIVOS_BACKUP]';
RESTORE DATABASE;
RELEASE CHANNEL CH01;
}