CONFIGURE DEVICE TYPE DISK PARALLELISM 4 BACKUP TYPE TO BACKUPSET ;
CONFIGURE MAXSETSIZE TO UNLIMITED;
CONFIGURE BACKUP OPTIMIZATION ON;
CONFIGURE CHANNEL 1 DEVICE TYPE DISK MAXPIECESIZE 5 G ;
CONFIGURE CHANNEL 2 DEVICE TYPE DISK MAXPIECESIZE 5 G ;
CONFIGURE CHANNEL 3 DEVICE TYPE DISK MAXPIECESIZE 5 G ;
CONFIGURE CHANNEL 4 DEVICE TYPE DISK MAXPIECESIZE 5 G ;